### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by benbernard** [moorederodeo/Unsong-In-Ebook-Format#1]
Thanks so much for doing this! Love it, any chance we can get this updated for the latest stuff? looks like its up to book 3 and chapter 50 now.

**Comment by DavidMirror** [comment]
Hey benbernard,
 Thanks for the kind words! I was planning on updating when Book 3 was complete (It doesn't look like it is?, not sure how to tell), but I've posted it now on the releases page. I had been doing it all by hand, but I found two scrapers here:
[https://github.com/bluej100/unsong-prince](https://github.com/bluej100/unsong-prince)
[https://github.com/JasonGross/unsong_scraper](https://github.com/JasonGross/unsong_scraper) 
I ended up using Jason Gross's version as it was closer to what I already had done manually. 
Thanks again, 
moored
